package rmabuddy.hibernate;
// Generated 2016-11-08 22:06:16 by Hibernate Tools 4.3.1



/**
 * Hardware generated by hbm2java
 */
public class Hardware  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer type;
     private Integer instore;
     private String sn;
     private String other;

    public Hardware() {
    }

	
    public Hardware(int id) {
        this.id = id;
    }
    public Hardware(int id, String name, Integer type, Integer instore, String sn, String other) {
       this.id = id;
       this.name = name;
       this.type = type;
       this.instore = instore;
       this.sn = sn;
       this.other = other;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getInstore() {
        return this.instore;
    }
    
    public void setInstore(Integer instore) {
        this.instore = instore;
    }
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }




}


