package rmabuddy.hibernate;
// Generated 2016-11-08 22:06:16 by Hibernate Tools 4.3.1



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int id;
     private String description;
     private String color;

    public Status() {
    }

	
    public Status(int id) {
        this.id = id;
    }
    public Status(int id, String description, String color) {
       this.id = id;
       this.description = description;
       this.color = color;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }




}


